#!/usr/bin/env node

export { Cli } from './cli.js'
export type { CliOptions } from './cli.js'
export { Session } from './session.js'
export { parseArgs } from './args.js'
export type { CliCommand, ParsedArgs } from './args.js'
export { loginCommand } from './login.js'
export type { LoginOptions } from './login.js'
export { whoamiCommand } from './whoami.js'
export { postCommand } from './post.js'
export type { PostInput } from './post.js'
export { scheduleCommand } from './schedule.js'
export type { ScheduleInput } from './schedule.js'
export { daemonCommand } from './daemon.js'
export type { DaemonInput, DaemonResult } from './daemon.js'
export { autoLoginFacebook } from './auto-login.js'
export type { AutoLoginOptions, AutoLoginResult } from './auto-login.js'
export { MockProvider } from './mock.js'
export { ProviderRegistry } from './registry.js'
export type { ProviderFactory } from './registry.js'
